const DATA = {

  /* Baybayin word list */
  words: [
    { baybayin:['ᜊ','ᜑ','ᜌ᜔'],           roman:'bahay',  meaning:'house',         points:100 },
    { baybayin:['ᜀ','ᜇ','ᜏ᜔'],           roman:'araw',   meaning:'sun / day',      points:100 },
    { baybayin:['ᜎ','ᜓ','ᜉ'],           roman:'lupa',   meaning:'earth / soil',   points:100 },
    { baybayin:['ᜉ','ᜓ','ᜐ','ᜓ'],           roman:'puso',   meaning:'heart',          points:110 },
    { baybayin:['ᜊ','ᜓ','ᜑ','ᜒ','ᜈ᜔'],     roman:'buhin',  meaning:'to erase',       points:120 },
    { baybayin:['ᜆ','ᜓ','ᜊ','ᜒ','ᜄ᜔'],      roman:'tubig',  meaning:'water',          points:120 },
    { baybayin:['ᜊ','ᜓ','ᜃ','ᜒ','ᜇ'],      roman:'bukid',  meaning:'farm / field',   points:120 },
    { baybayin:['ᜄ','ᜓ','ᜎ','ᜓ'],           roman:'gulo',   meaning:'chaos',          points:110 },
    { baybayin:['ᜋ','ᜓ','ᜃ᜔','ᜑ'],      roman:'mukha',  meaning:'face',           points:130 },
    { baybayin:['ᜇ','ᜒ','ᜏ'],           roman:'diwa',   meaning:'spirit / soul',  points:140, bonus:true },
    { baybayin:['ᜑ','ᜒ','ᜋ'],           roman:'hima',   meaning:'to stroke',      points:110 },
    { baybayin:['ᜐ','ᜓ','ᜎ','ᜒ'],           roman:'suli',   meaning:'to return',      points:110 },
    { baybayin:['ᜃ','ᜓ','ᜃ','ᜓ'],           roman:'kuko',   meaning:'fingernail',     points:100 },
    { baybayin:['ᜉ','ᜒ','ᜆ'],           roman:'pita',   meaning:'desire',         points:100 },
    { baybayin:['ᜋ','ᜓ','ᜎ'],           roman:'mula',   meaning:'from / origin',  points:100 },
    { baybayin:['ᜑ','ᜒ','ᜉ','ᜓ','ᜈ᜔'],     roman:'hipon',  meaning:'shrimp',         points:130 },
    { baybayin:['ᜆ','ᜓ','ᜄ','ᜓ'],           roman:'tugo',   meaning:'to match',       points:110 },
    { baybayin:['ᜅ','ᜒ','ᜐ','ᜒ','ᜆ᜔'],    roman:'ngisit', meaning:'to grin',        points:160, bonus:true },
    { baybayin:['ᜁ','ᜊ','ᜓ'],               roman:'ibu',    meaning:'to carry',       points: 80 },
    { baybayin:['ᜃ','ᜓ','ᜆ','ᜒ','ᜉ᜔'],    roman:'kutip',  meaning:'to pick up',     points:130 },
    { baybayin:['ᜑ','ᜒ','ᜈ','ᜒ'],           roman:'hini',   meaning:'to ask gently',  points:110 },
    { baybayin:['ᜉ','ᜓ','ᜆ','ᜓ'],           roman:'puto',   meaning:'rice cake',      points:100 },
    { baybayin:['ᜊ','ᜓ','ᜃ','ᜓ'],           roman:'buko',   meaning:'young coconut',  points:100 },
    {baybayin:['ᜀ','ᜉ','ᜓ','ᜌ᜔'],         roman:'apoy',   meaning:'fire',           points:100 },
    { baybayin:['ᜎ','ᜒ','ᜉ','ᜓ'],           roman:'lipu',   meaning:'to turn away',   points:110 },
    {baybayin:['ᜊ','ᜆ','ᜓ'],               roman:'bato',   meaning:'stone',          points:100},
    {baybayin['ᜑ','ᜅ','ᜒ','ᜈ᜔'],          roman:'hangin',   meaning:'air',          points:110},
  ],

  /* ─ Tile pool ─ */
  tilePool: [
    { char:'ᜀ', roman:'a'   },
    { char:'ᜁ', roman:'i'   },
    { char:'ᜂ', roman:'u'   },
    { char:'ᜃ', roman:'ka'  },
    { char:'ᜄ', roman:'ga'  },
    { char:'ᜅ', roman:'nga' },
    { char:'ᜆ', roman:'ta'  },
    { char:'ᜇ', roman:'da'  },
    { char:'ᜈ', roman:'na'  },
    { char:'ᜉ', roman:'pa'  },
    { char:'ᜊ', roman:'ba'  },
    { char:'ᜋ', roman:'ma'  },
    { char:'ᜌ᜔', roman:'y'  },
    { char:'ᜍ', roman:'ra'  },
    { char:'ᜎ', roman:'la'  },
    { char:'ᜏ', roman:'wa'  },
    { char:'ᜐ', roman:'sa'  },
    { char:'ᜑ', roman:'ha'  },
    { char:'ᜒ', roman:'i'   },
    { char:'ᜓ', roman:'u'   },
    { char:'ᜈ᜔', roman:'n' },
    { char:'ᜆ᜔', roman:'t' },
    { char: 'ᜃ᜔', roman: 'k' },
    { char: 'ᜏ᜔', roman: 'w' },
    { char:'ᜉ᜔', roman:'p' },
    { char:'ᜄ᜔', roman:'g'},
  ],

  commonChars: ['ᜀ','ᜁ','ᜂ','ᜃ','ᜆ','ᜈ','ᜉ','ᜊ','ᜋ','ᜎ','ᜑ','ᜒ','ᜓ'],

  /* ─ Enemies ─ */
  enemies: [
    {
      name: 'Pebble Frog',
      image: 'img/Pebble_frog.png',
      lore: 'A pebble frog hides along dirt roads, covering itself with loose stones to blend seamlessly into the ground and stay safe from predators.',
      maxHP: 3,
      moves: ['Jump','Shapeshift','Snarl'],
      svgColor: '#482e09ff',
      chapter: 1,
    },
    {
      name: 'Bubble Tarsier',
      image: 'img/Bubble_tarsier.png',
      lore: 'A bubble tarsier lives along shallow coral reefs, perching on coral branches near the shore. It forms clear bubbles over its large eyes like goggles, blocking saltwater so it can see underwater.',
      maxHP: 4,
      moves: ['Pound','Illusion','Hydrate'],
      svgColor: '#31a275ff',
      chapter: 1,
    },
    {
      name: 'Fire Swallow',
      image: 'img/Fire_swallow.png',
      lore: 'A fire swallow soars through the night with a crown of fire, leaving a trail of embers that guide lost travelers back to safety.',
      maxHP: 5,
      moves: ['Scratch','Guide','Bright Screech'],
      svgColor: '#e07510ff',
      chapter: 2,
    },
    {
      name: 'Cloud Turtle',
      image: 'img/Cloud_turtle.png',
      lore: 'A cloud turtle drifts slowly across mountain skies, its body is light enough to float on gentle winds. Instead of a shell, it envelopes itself with a light, fluffy cloud on its back instead.',
      maxHP: 6,
      moves: ['Smash','Smoke Cloud','Thunderstrike'],
      svgColor: '#57b4d5ff',
      chapter: 2,
    },
  ],

  /* ─ Chapters ─ */
  chapters: [
    { title:'Chapter 1: The Enchanted Forest',  enemyIndices:[0,1] },
    { title:'Chapter 2: Silent Woods',  enemyIndices:[2,3] },
  ],
};